version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ams-service
      POSTGRES_USER: ams-user
      POSTGRES_PASSWORD: 26538hsvgn8p
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "6543:5432"