version: '3'
services:
  psql-ams:
    image: postgres:latest
    environment:
      POSTGRES_DB: ams-service
      POSTGRES_USER: ams-user
      POSTGRES_PASSWORD: 26538hsvgn8p
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3232:5432"

  app:
    build: .
    ports:
      - "9033:9033"
      - "8012:8012"
    environment:
      - CONFIG_PATH=./config/config.yaml
    depends_on:
      - psql-ams